"use client";

// Generated by GitHub Copilot
import React, { useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { IoClose, IoSend } from "react-icons/io5";

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
};

type ChatBotProps = {
  open: boolean;
  onClose: () => void;
};

/**
 * Sanitize user input to mitigate prompt-injection and oversize payloads
 * before sending to the server-side chat API.
 */
function sanitizeInput(text: string): string {
  return text.replace(/[\u0000-\u001F\u007F]/g, " ").slice(0, 1000).trim();
}

/**
 * Call the server-side /api/chat route, which proxies to the configured
 * free LLM provider (Groq) using a key that never leaves the server.
 */
async function askLLM(history: ChatMessage[], signal: AbortSignal): Promise<string> {
  const res = await fetch("/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ messages: history }),
    signal,
  });

  const data = await res.json().catch(() => null);
  if (!res.ok) {
    throw new Error(data?.error ?? `Request failed (${res.status})`);
  }
  const reply: unknown = data?.reply;
  if (typeof reply === "string" && reply.trim()) return reply.trim();
  return "Sorry, I couldn't generate a response right now.";
}

export default function ChatBot({ open, onClose }: ChatBotProps) {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      role: "assistant",
      content:
        "Hi! I'm Pradhumn with better sense of humour. Ask me anything about Pradhumn Pande or just say hi! 😊",
    },
  ]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, loading, open]);

  useEffect(() => {
    return () => abortRef.current?.abort();
  }, []);

  /**
   * Submit user message: validates, updates UI optimistically, and queries the LLM.
   */
  async function handleSend(e?: React.FormEvent) {
    e?.preventDefault();
    const clean = sanitizeInput(input);
    if (!clean || loading) return;

    const next: ChatMessage[] = [...messages, { role: "user", content: clean }];
    setMessages(next);
    setInput("");
    setLoading(true);

    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;

    try {
      const reply = await askLLM(next, controller.signal);
      setMessages((m) => [...m, { role: "assistant", content: reply }]);
    } catch (err) {
      if ((err as Error).name !== "AbortError") {
        setMessages((m) => [
          ...m,
          {
            role: "assistant",
            content:
              "Hmm, This idiot forgot to buy credits, Until then please go through Portfolio page ",
          },
        ]);
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <AnimatePresence>
      {open && (
        <motion.div
          role="dialog"
          aria-label="Chat with Pradhumn's assistant"
          aria-modal="false"
          initial={{ opacity: 0, y: 20, scale: 0.95 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 20, scale: 0.95 }}
          transition={{ type: "tween", duration: 0.2 }}
          className="fixed bottom-6 right-6 z-[60] w-[22rem] max-w-[calc(100vw-2rem)] h-[28rem] flex flex-col rounded-2xl shadow-2xl border border-black/10 bg-white/90 backdrop-blur-md dark:bg-gray-900/90 dark:border-white/10"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-black/10 dark:border-white/10">
            <div className="flex items-center gap-2">
              <span
                className="inline-block w-2.5 h-2.5 rounded-full bg-green-500"
                aria-hidden="true"
              />
              <h2 className="font-semibold text-gray-900 dark:text-white">
                Pradhumn's Assistant
              </h2>
            </div>
            <button
              type="button"
              onClick={onClose}
              aria-label="Close chat"
              className="p-1 rounded-full text-gray-600 hover:text-gray-900 hover:bg-black/5 dark:text-white/60 dark:hover:text-white dark:hover:bg-white/10 transition focus:outline-none focus:ring-2 focus:ring-gray-400"
            >
              <IoClose size={20} />
            </button>
          </div>

          {/* Messages */}
          <div
            ref={scrollRef}
            className="flex-1 overflow-y-auto px-3 py-3 space-y-2"
            aria-live="polite"
          >
            {messages.map((m, i) => (
              <div
                key={i}
                className={`flex ${
                  m.role === "user" ? "justify-end" : "justify-start"
                }`}
              >
                <div
                  className={`max-w-[80%] px-3 py-2 rounded-2xl text-sm whitespace-pre-wrap break-words ${
                    m.role === "user"
                      ? "bg-gray-900 text-white rounded-br-sm dark:bg-white dark:text-gray-900"
                      : "bg-gray-100 text-gray-900 rounded-bl-sm dark:bg-white/10 dark:text-white/90"
                  }`}
                >
                  {m.content}
                </div>
              </div>
            ))}
            {loading && (
              <div className="flex justify-start">
                <div className="px-3 py-2 rounded-2xl bg-gray-100 text-gray-600 text-sm dark:bg-white/10 dark:text-white/70">
                  <span className="inline-flex gap-1">
                    <span className="w-1.5 h-1.5 rounded-full bg-current animate-bounce [animation-delay:-0.3s]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-current animate-bounce [animation-delay:-0.15s]" />
                    <span className="w-1.5 h-1.5 rounded-full bg-current animate-bounce" />
                  </span>
                </div>
              </div>
            )}
          </div>

          {/* Input */}
          <form
            onSubmit={handleSend}
            className="flex items-center gap-2 p-3 border-t border-black/10 dark:border-white/10"
          >
            <label htmlFor="pradbot-input" className="sr-only">
              Type your message
            </label>
            <input
              id="pradbot-input"
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask me anything…"
              maxLength={1000}
              disabled={loading}
              className="flex-1 px-3 py-2 text-sm rounded-full bg-gray-100 text-gray-900 placeholder:text-gray-500 outline-none focus:ring-2 focus:ring-gray-400 dark:bg-white/10 dark:text-white dark:placeholder:text-white/40"
            />
            <button
              type="submit"
              disabled={loading || !input.trim()}
              aria-label="Send message"
              className="p-2 rounded-full bg-gray-900 text-white disabled:opacity-40 hover:bg-gray-700 active:scale-95 transition dark:bg-white dark:text-gray-900 dark:hover:bg-white/80 focus:outline-none focus:ring-2 focus:ring-gray-400"
            >
              <IoSend size={16} />
            </button>
          </form>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
